### ISSUE TITLE
Outdated release notes

### ISSUE THREAD

**Issue by exalted** [awsdocs/amazon-elasticsearch-service-developer-guide#15]
When I clicked on the GitHub button at the top of this page https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/release-notes.html#release-table I was expecting to find https://github.com/awsdocs/amazon-elasticsearch-service-developer-guide/blob/master/doc_source/release-notes.md up-to-date. However those two seem to be very different from each other.

* Perhaps there's a new source for those page(s)?
* Although in AWS-managed ES console the message "A new service software release R20190113 is available." appears, but https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/release-notes.html#release-table doesn't include it?

Thank you.

**Comment by aetter** [comment]
Hi @exalted, thanks for bringing this up. The process of getting updated MD files onto GitHub is a bit convoluted and tedious, so they go out of date from time to time. I just pushed new content to bring *most* things up to date.

Unfortunately, this new content doesn't include the release note for R20190113. I'm aware of the content gap and am working on a fix. Thanks again!

**Comment by exalted** [comment]
👍

**Comment by aetter** [comment]
Hi @exalted, just pushed up the missing note. Closing this out. Thanks again! https://github.com/awsdocs/amazon-elasticsearch-service-developer-guide/commit/a4efaee791fa6341c6a301412f8b07bc15575552
