### ISSUE TITLE
No description for service update R20190221-P1

### ISSUE THREAD

**Issue by Jeeppler** [awsdocs/amazon-elasticsearch-service-developer-guide#17]
I received an service update with the name `R20190221-P1`. However, there is no description for this upgrade in the release notes: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/release-notes.html#release-table

Region: us-west-2 (Oregon)

What does `R20190221-P1` provide?

**Comment by aetter** [comment]
Hi @Jeeppler, it just fixes a couple bugs that were introduced in the 0221 release. Change is rolling out to the Amazon ES docs now.

**Comment by Jeeppler** [comment]
I want to know what fixed and bugs are fixed so I am able to report issues to OpenDistribution for ElasticSearch and not report already fixed issues. Knowing what updates include is important to me.

**Comment by Jeeppler** [comment]
Please close this issue after you successfully rolled out the changes to the doc and not before.
