### ISSUE TITLE
Access policy sample in es-kibana.md leads to error "can’t attach an IP-based policy"

### ISSUE THREAD

**Issue by Timslhsu** [awsdocs/amazon-elasticsearch-service-developer-guide#2]
In the section "Using a Proxy to Access Amazon ES from Kibana", it mentioned applying "a resource-based policy that specifies roles and IP addresses" to ES domain. However, an ES domain with VPC endpoint does not support IP-based access policy. When applying this, user will get the error message like below.
```
UpdateElasticsearchDomainConfig: {"message":"You can’t attach an IP-based policy to a domain that has a VPC endpoint. Instead, use a security group to control IP-based access."}
```
This paragraph and sample should be corrected.

**Comment by aetter** [comment]
Hi @Timslhsu, thanks for reporting. Resolved in: https://github.com/awsdocs/amazon-elasticsearch-service-developer-guide/commit/a033da866dff1251a42aa1637b89e7ebcc5fc779#diff-861cbf8ba5a0dc5589e8ef3d5cf74a1e
