### ISSUE TITLE
ES CreateServiceLinkedRole

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/amazon-elasticsearch-service-developer-guide#20]
As @andywickersham pointed out here,

https://github.com/awsdocs/iam-user-guide/issues/163

Creating a Service Linked Role for ES uses this API call es:CreateElasticsearchServiceRole.  Should this documentation be changed to reflect that?

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/slr-es.html

**Comment by aetter** [comment]
Thanks @jsoncow. I've resolved this issue in the developer guide, but changes to the IAM guide will take longer to propagate.
