### ISSUE TITLE
Connecting a Local Kibana Server to Amazon ES section contains wrong instructions

### ISSUE THREAD

**Issue by NikitaGl** [awsdocs/amazon-elasticsearch-service-developer-guide#21]
According to documentation section, to connect local Kibana to AWS ES host, I need to configure it to http endpoint, but it will not work that way, instead, I've come up with working local Kibana only using https endpoint and ES version 7. Version 6 does not work both ways. This section definitely needs an update, since even config example has wrong config section names.

**Comment by aetter** [comment]
Hi @NikitaGl, thanks a bunch for the heads-up. Looks like this changed under the hood on us.

I've added some additional notes to help people get configured, but it varies so much version by version that I suspect some fiddling will still be required: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-kibana.html#es-kibana-local
