### ISSUE TITLE
The Shard Calculations are not applied to cluster sizing estimation

### ISSUE THREAD

**Issue by ecout** [awsdocs/amazon-elasticsearch-service-developer-guide#22]
In this file:
https://github.com/awsdocs/amazon-elasticsearch-service-developer-guide/blob/master/doc_source/sizing-domains.md

The first two sections describe how to calculate the Minimum required storage and the Shard Count based on total storage size of the cluster.  

The document then proceeds to give a "general guidance" about how to choose instance types and number with no obvious direct linking to the information presented in the two previous sections, especially the information regarding shards.

The examples in the last section are vague and do not leverage the information provided in the document up to the point to make a concise explanation.

As an example of vagueness consider this Item:

> If you have a 184 GiB storage requirement and the recommended minimum number of three instances, use the equation 184 / 3 = 61 GiB to find the amount of storage that each instance needs. In this example, you might select three m4.large.elasticsearch instances for your cluster, each using a 90 GiB EBS storage volume so that you have a safety net and some room for growth over time. This configuration provides 6 vCPU cores and 24 GiB of memory, so it's suited to lighter workloads.

> For a more substantial example, consider a 14 TiB storage requirement and a heavy workload. In this case, you might choose to begin testing with 2 * 144 = 288 vCPU cores and 8 * 144 = 1152 GiB of memory. These numbers work out to approximately 18 i3.4xlarge.elasticsearch instances. If you don't need the fast, local storage, you could also test 18 r5.4xlarge.elasticsearch instances, each using a 1 TiB EBS storage volume.

Where does the number 144 came from?
Why is the shard information ignored in the estimation examples? Is it there but not clearly obvious?

The document leaves the reader feeling more like they're back at square 1 before they started reading.

**Comment by aetter** [comment]
Hi @ecout, one of the more common issues we encounter is users sizing shards inappropriately. Plus, shard size has some influence on the number of nodes you choose. You can imagine a situation in which someone with 100 GiB of data decides that two 50 GiB shards is appropriate on a three-node cluster, which leaves one node severely underutilized. So even if it doesn't *directly* impact the node types and number of nodes, having a working understanding of shards is critical to operating a cluster. Though it might seem disconnected, it's important prior knowledge that users need to have prior to testing and validating their clusters.

For the 144 number, agreed that it's non-obvious. 14 TiB is 14336 GiB, rounded up to 14400, then divided by 100 for a heavy workload. I've added a quick note that provides the TiB value in GiB.
